---
title: "01 Case Study Object Review"
author: "ZHANG ZHOU"
date: "2023-12-01"
output:
  html_document: 
    highlight: espresso
---

<hr style="border:1px solid lightgrey">

## Background

This is the **capstone project** for Google Data Analytics Certificate.

I select **Case Study 1** for this this project:

-   [How Does a Bike-Share Navigate Speedy Success?]{style="background-color: yellow;"}

\

Below is the information from the case study packet:

#### - Scenario

You are a junior data analyst working in the marketing analyst team at Cyclistic, a bike-share company in Chicago. The director of marketing believes the company's future success depends on maximizing the number of annual memberships. Therefore, your team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, your team will design a new marketing strategy to convert casual riders into annual members. But first, Cyclistic executives must approve your recommendations, so they must be backed up with compelling data insights and professional data visualizations.

\

#### - Characters and teams

-   **Cyclistic:** A bike-share program that features more than 5,800 bicycles and 600 docking stations. Cyclistic sets itself apart by also offering reclining bikes, hand tricycles, and cargo bikes, making bike-share more inclusive to people with disabilities and riders who can't use a standard two-wheeled bike. The majority of riders opt for traditional bikes; about 8% of riders use the assistive options. Cyclistic users are more likely to ride for leisure, but about 30% use them to commute to work each day.

-   **Lily Moreno:** The director of marketing and your manager. Moreno is responsible for the development of campaigns and initiatives to promote the bike-share program. These may include email, social media, and other channels.

-   **Cyclistic marketing analytics team:** A team of data analysts who are responsible for collecting, analyzing, and reporting data that helps guide Cyclistic marketing strategy. You joined this team six months ago and have been busy learning about Cyclistic's mission and business goals --- as well as how you, as a junior data analyst, can help Cyclistic achieve them.

-   **Cyclistic executive team:** The notoriously detail-oriented executive team will decide whether to approve the recommended marketing program.

\

#### - About the company

In 2016, Cyclistic launched a successful bike-share offering. Since then, the program has grown to a fleet of 5,824 bicycles that are geo tracked and locked into a network of 692 stations across Chicago. The bikes can be unlocked from one station and returned to any other station in the system anytime. Until now, Cyclistic's marketing strategy relied on building general awareness and appealing to broad consumer segments. One approach that helped make these things possible was the flexibility of its pricing plans: single-ride passes, full-day passes, and annual memberships. Customers who purchase single-ride or full-day passes are referred to as casual riders. Customers who purchase annual memberships are Cyclistic members.

Cyclistic's finance analysts have concluded that annual members are much more profitable than casual riders. Although the pricing flexibility helps Cyclistic attract more customers, Moreno believes that maximizing the number of annual members will be key to future growth. Rather than creating a marketing campaign that targets all-new customers, Moreno believes there is a very good chance to convert casual riders into members. She notes that casual riders are already aware of the Cyclistic program and have chosen Cyclistic for their mobility needs.

Moreno has set a clear goal: Design marketing strategies aimed at converting casual riders into annual members. In order to do that, however, the marketing analyst team needs to better understand how annual members and casual riders differ, why casual riders would buy a membership, and how digital media could affect their marketing tactics. Moreno and her team are interested in analyzing the Cyclistic historical bike trip data to identify trends.

------------------------------------------------------------------------

## Object review

The **key object** of the company stakeholders is:

-   Increase [revenue]{.underline} and improve [profitability]{.underline} by increasing the [number of annual members]{.underline}.

In my view, there are 3 approaches to increase the number of annual members:

1.  **Convert casual members to annual members.**

    -   This is the exact task put forward to me.

2.  **Retain current annual members.**

    -   Though it will not increase the total number of annual members, it is still important.

3.  **Increase total membership.**

    -   Even though new members may be mostly casual, bigger casual membership base may enhance the effect of the actions to convert casual members to annual ones.

------------------------------------------------------------------------

## Hypothesis and ideas

Now we focus on the key task: **How to convert casual members to annual members?**

Let's start by answering below questions:

#### [1. How do annual members and casual riders use Cyclistic bikes differently?]{style="color: blue;"}

-   Difference in **number of rides**

    -   ([Hypothesis]{style="background-color: lightgrey;"}) On average casual riders use Cyclistic bikes less frequently

-   Difference in **bike type** preference

-   Difference in riding **time pattern**

    -   Is there any seasonal trend?

    -   ([Hypothesis]{style="background-color: lightgrey;"}) Casual riders tends to ride more on weekends

    -   ([Hypothesis]{style="background-color: lightgrey;"}) Annual members use the bikes more for weekday daily commutes to and from work during peak hours.

-   Difference in **trip length**

    -   ([Hypothesis]{style="background-color: lightgrey;"}) Casual riders, especially full-day pass holders tend to have longer trip for exercise or recreation purpose.

-   Difference in geographical distribution

    -   ([Idea]{style="background-color: lightgrey;"}) If to put up physical ads like posters, better to focus on the locations near the most popular stations and routes for casual riders.

-   ([Idea]{style="background-color: lightgrey;"}) Study the behavior change of users **before and after** they **convert to annual members**

    -   This data may be very useful to understand why they want to convert.

\

#### [2. Why would casual riders buy Cyclistic annual memberships?]{style="color: blue;"}

-   ([Hypothesis]{style="background-color: lightgrey;"}) Riders buy annual memberships to **save money**.

    -   ([Idea]{style="background-color: lightgrey;"}) Send promotion email or app push notice to show how much they can save by signing up annual membership.

    -   ([Idea]{style="background-color: lightgrey;"}) Provide bundle discount to encourage all family members to join annual membership.

    -   ([Idea]{style="background-color: lightgrey;"}) Provide discount for referring friends to join annual membership.

-   ([Hypothesis]{style="background-color: lightgrey;"}) Encourage riders to **ride more** will be helpful on the conversion rate.

    -   ([Idea]{style="background-color: lightgrey;"}) Promote healthy life style, send customized email or app push notice to show:

        1.  How much cycling they have done and the number of calories burnt.

        2.  Recommended cycling routes and locations for site viewing or recreation activities near the specific rider (judging from address or frequent biking routes)

    -   ([Idea]{style="background-color: lightgrey;"}) Use shared bikes for last mile commute can help users **save time**. Include the estimate time saved by riding with Cyclistic in the weekly or monthly summary report email or push notice can encourage the customers to ride more frequently.

-   ([Idea]{style="background-color: lightgrey;"}) Add **extra benefit** to annual membership

    -   ([Idea]{style="background-color: lightgrey;"}) Add premiere app function of sharing a trip story (route, length, calories burnt, nice photos of great landscapes and happy activities from web or personal album) on popular social apps.

    -   ([Idea]{style="background-color: lightgrey;"}) Reserve a certain ratio of bikes for annual members only.

        -   In case some popular location has limited number of bikes, this policy will ensure annual members to have higher possibility of availability to a bike.

        -   [**Caution**:]{style="color: red;"} This policy may have negative effect on casual riders, so need to study carefully.

\

#### [3. How can Cyclistic use digital media to influence casual riders to become members?]{style="color: blue;"}

-   ([Idea]{style="background-color: lightgrey;"}) Weekly or monthly summary report customized for each customer, including:

    -   Total trip counts, total mileage, total colories burnt, total time saving (compare to walking), etc.

    -   Frequent locations (based on most visisted stations and routes) and top trip stories shared by other annual members from there.

    -   Recommend routes for excercise or recreation riding journey.

    -   Smartly embed ads for annual membership.

        -   For casual members, show how they can save time and money by upgrading to annual membership.

        -   For annual members, show discount for family bundles and reward for friends reference.

-   ([Idea]{style="background-color: lightgrey;"}) Setup official Cyclistic accounts on all major social media and encourage customers to follow.

    -   Share tips and tricks of using Cyclistic bikes, smartly embed ads to promote annual membership.

    -   Share selected nice trip stories and encourage followers to vote for the best one.

    -   Periodically arrange events of group riding journey at weekends and holidays.

        -   Help members to social through Cyclistic platform

        -   If successful, should be able to increase average riding per member.

\

------------------------------------------------------------------------

Now we are ready to collect the necessary data to test our hypothesis and verify the feasibility of our ideas.

Please note actual data may inspire new hypothesis and ideas.

In step 02 of this case study we shall review the data provided, choose suitable tools and perform data cleaning.

\
\
